######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 24 19:28:28 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
QT += network webkit
#CONFIG += console